name = "fgof-temp"
version = "0.1.0"
license = "MIT"
author = "FortranGoingOnForty"
maintainer = "FortranGoingOnForty"
copyright = "2026"
description = "Temp files and atomic writes for modern Fortran"

[build]
auto-executables = false
auto-tests = true
auto-examples = true

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
